# Generated by Django 4.2.2 on 2023-12-22 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_log_delete_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='password',
        ),
    ]
